apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetdemo-deployment 
  labels:
    app: dotnetdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnetdemo
  template:
    metadata:
      labels:
        app: dotnetdemo
    spec:
      containers:
        - name: my-container
          image: my-image
      imagePullSecrets:
        - name: my-secret