apiVersion: v1
kind: Service
metadata:
  name: dotnetdemo
  namespace: bhuvana
spec:
  selector:
    app: dotnetdemo
    type: Loadbalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000